# Generated by Django 4.2.19 on 2025-03-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_forumpost_id_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
