# Generated by Django 4.2.19 on 2025-03-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_alter_forumpost_user_alter_mentorship_mentee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_languages',
            field=models.ManyToManyField(blank=True, help_text='Select the languages the user is proficient in.', to='homeapp.language'),
        ),
    ]
