# Generated by Django 4.2.19 on 2025-03-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_language_customuser_preferred_languages'),
        
    ]

    operations = [
    ]
