# Generated by Django 4.2.19 on 2025-03-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_merge_20250322_1417'),
        ('homeapp', '0007_merge_20250322_2351'),
    ]

    operations = [
    ]
